### ISSUE TITLE
CachedResponse is unpicklable when `history` is non-null

### ISSUE THREAD

**Issue by Jophish** [JWCook/aiohttp-client-cache#1]
When `history` exists for a `ClientResponse` object, the corresponding `CachedResponse` cannot be pickled when saving to the backend, since `CachedResponse.history` is being saved as a generator. I think the intention was to save it as a tuple, but the current syntax used represents a generator expression. Even if it's modified to become a tuple, it's still unpicklable since `history` will be a tuple of coroutines unless we `await` the recursive calls. Will try to get a PR out to fix this.

**Comment by JWCook** [comment]
@Jophish Cool, thanks! I'm surprised someone found this so quickly; I've only worked on this for about a week. Redirect history is one of the many things I hadn't tested yet, so thanks for saving me some time there.

**Comment by Jophish** [comment]
Of course! I just migrated a project from `requests` and `requests-cache` to `aiohttp` and was surprised there wasn't a ubiquitous caching library for it, and then stumbled on this -- seemingly perfect timing!

**Comment by JWCook** [comment]
@Jophish Same here, I was surprised this didn't already exist!

I'm spending some time this weekend cleaning up some of the half-finished bits and tasking out the remaining work to do. If you're interested, feel free to pick up any of the open issues, or anything else you can identify that needs to be done. Or, if you'd like to review what I've done so far, a second pair of eyes on this code would be helpful.
