### ISSUE TITLE
Enable GitHub Discussions for a repository

### ISSUE THREAD

**Issue by AIGeneratedUsername** [JWCook/aiohttp-client-cache#107]
[Quickstart for GitHub Discussions](https://docs.github.com/en/discussions/quickstart)

[Enabling or disabling GitHub Discussions for a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository)

**Comment by JWCook** [comment]
Done!
