### ISSUE TITLE
Feature request: Read some parameters from environmental variables

### ISSUE THREAD

**Issue by cheginit** [JWCook/aiohttp-client-cache#112]
### Use case
_Is there a specific goal that this would help you accomplish, or can you provide any other context about how you would like to use this feature?_
I've developed a stack of Python packages one of which is a high-level API to `atiohttp-client-cache` for for some specific purposes called [AsyncRetriever](https://github.com/cheginit/async_retriever). It use this in all my other packages for making web calls. Currently, I have two arguments related to caching in all the functions that make web calls. So, to make things much easier, I am to replace those arguments by reading three caching-related parameters using environmental variables: `expire_after`, `disable`, and `cache_name`. This makes things much easier for users to set this globally rather than making the changes for each function.

I am thinking maybe it would be a nice feature to implement in `atiohttp-client-cache`.

### Workarounds
_Is there an existing workaround to accomplish this?_

### Plan to implement
_Are you interested in submitting a PR to implement this?_
I can do do if there's interest.

**Comment by JWCook** [comment]
I also like using environment variables for config, but generally I think that belongs more at the application or framework level, not in a library. There are so many different ways to provide config (envars, JSON/YAML/INI config files, cloud provider-specific config services, etc.), and the best option really depends on the application.

It's easy enough to set this up yourself, though. You can put something like this in, say, `my_app/config.py`:
```python
import os
from contextlib import asynccontextmanager
from aiohttp import ClientSession
from aiohttp_client_cache import CachedSession, SQLiteBackend

# The cache backend object can be defined as a singleton,
# and doesn't require an async context to create
CACHE = SQLiteBackend(
    os.getenv('HYRIVER_CACHE_NAME', 'default_cache_name'),
    expire_after=int(os.getenv('HYRIVER_CACHE_EXPIRE', 360)),
)

@asynccontextmanager
async def get_session():
    cache_disabled = os.getenv('HYRIVER_CACHE_DISABLE', '').lower() == 'true'
    async with (ClientSession() if cache_disabled else CachedSession(cache=CACHE)) as session:
        yield session
```

Then, in some module where you're making requests:
```python
from my_app.config import get_session

async def foo(url):
    async with get_session() as session:
        return await session.get(url)
```

Does that help?

**Comment by JWCook** [comment]
Very cool project(s), by the way. My day job at Corteva is data science-adjacent, and involves some geospatial data analysis. We've open-sourced a few pieces of that, like [rioxarray](https://github.com/corteva/rioxarray) and [geocube](https://github.com/corteva/geocube). I don't do any watershed analysis myself, but it looks like a lot of the libraries you use overlap with the ones used here. Looks like fun. Good luck with that!

**Comment by cheginit** [comment]
Yes, it was very helpful. Thanks. That's exactly what I was thinking but more elegant!

Ah, I didn't know that you work at Corteva, that's very cool! I actually use `rioxarray` in my packages. It would be interesting to know the overlaps and hopefully find some common interests that can benefit the community.
