### ISSUE TITLE
How to combine with https://github.com/inyutin/aiohttp_retry

### ISSUE THREAD

**Issue by foooooooooooooooobar** [JWCook/aiohttp-client-cache#16]
Hey! Thanks for the library, I was wondering if it's possible to use the retry and cache libraries together?

**Comment by JWCook** [comment]
Good question! Yes, there would be a few different ways to combine these. This library subclasses `ClientSession`, and it looks like `aiohttp_retry` wraps a `ClientSession` with a wrapper class. So, the quick and ugly way would be to monkey-patch `RetryClient`'s inner `ClientSession`:

```python
import aiohttp_retry
import aiohttp_client_cache

aiohttp_retry.ClientSession = aiohttp_client_cache.CachedSession
client = aiohttp_retry.RetryClient(**kwargs)
```

That *should* give you both caching and retry features, but I haven't tested it yet.

**Comment by JWCook** [comment]
A better and more pythonic solution, I believe, would be to refactor both `CachedSession` and `RetrySession` to be mixin classes, instead of a subclass and wrapper class, respectively. Then you could do something like this:
```python
Class CustomSession(ClientSession, RetryMixin, CacheMixin):
    ...
```

**Comment by JWCook** [comment]
Fyi, `aiohttp_client_cache.CacheMixin` has been added for this purpose.

Closing this issue for now; let me know if the above answers your question.
