### ISSUE TITLE
CachedResponse.headers are case-sensitive and do not support multiple values for the same key

### ISSUE THREAD

**Issue by akursar** [JWCook/aiohttp-client-cache#28]
CachedResponse's headers attribute is a regular dict. This makes it case sensitive and does not support multiple values for the same key. The original ClientSession makes this available through a CIMultiDictProxy and it's called out in aiohttp's docs: https://docs.aiohttp.org/en/stable/client_advanced.html#response-headers-and-cookies
The multiple values may be an edge case, but it breaks compatibility for users who use the getall method on the headers object. The case sensitivity has greater impact, producing misses when you use a different case for "content-type" or "cache-control".

**Comment by akursar** [comment]
Thanks for this lib, @JWCook ! I'm looking forward to using it but have only started to poke around. We're long-time users of https://github.com/ionrock/cachecontrol for requests and have been looking for something similar as we migrate to aiohttp.

**Comment by JWCook** [comment]
Thanks for the heads up! That should be easy enough to fix.

This library is still pretty early in development and I wouldn't consider it quite production-ready yet, but I'm happy to help if/when you run into more more issues (which is likely!). Also note that this doesn't respect cache headers like CacheControl does, but that's a feature I would like to add eventually.

**Comment by JWCook** [comment]
Ah, now I remember why I didn't use `CIMultiDictProxy` in the first place: it can't be pickled. I'm not too familiar with the inner workings of `multidict`.

@akursar If headers were serialized as a `{str: tuple}`  dict when writing to the cache, and then used to make a new `CIMultiDict` when deserialized, would that be good enough? Or would that potentially lose some information?

**Comment by akursar** [comment]
> Thanks for the heads up! That should be easy enough to fix.
> 
> This library is still pretty early in development and I wouldn't consider it quite production-ready yet, but I'm happy to help if/when you run into more more issues (which is likely!). Also note that this doesn't respect cache headers like CacheControl does, but that's a feature I would like to add eventually.

Right, I was playing around with this to respect the max-age header which would suit my limited needs, but I'm not sure if there are better patterns for extracting this from the headers. This is what uncovered this issue though.

    class MaxAgeExpiryMixin:
    @staticmethod
    def _get_max_age(response: ClientResponse) -> Optional[int]:
        cache_control_headers = response.headers.getall("Cache-Control") if "Cache-Control" in response.headers else None
        if not cache_control_headers:
            return None
        for header in cache_control_headers:
            parts = header.split('=')
            if parts[0] == "max-age":
                return int(parts[1])

    def get_expiration_date(self, response: ClientResponse) -> Optional[datetime]:
        date_header = response.headers.get("Date")
        if not date_header:
            return None
        max_age = self._get_max_age(response)
        if not max_age:
            return None
        resp_dt = datetime(*parsedate(date_header)[:6])
        return resp_dt + timedelta(seconds=max_age)

I have this in a local branch where I'm doing a bunch of other custom stuff and some workarounds. I'm going to start breaking it up into smaller individual pieces as separate items to start. Heads up that we use dynamodb as a cache in our aws lambda functions and so can potentially help out with the issue for that.

**Comment by akursar** [comment]
> Ah, now I remember why I didn't use `CIMultiDictProxy` in the first place: it can't be pickled.
> 
> @akursar I'm not too familiar with the inner workings of `multidict`, but if headers were serialized as a `{str: tuple}` dict when writing to the cache, and then used to make a new `CIMultiDict` when deserialized, would that be good enough? Or would that potentially lose some information? Or do you have suggestions for a different format to use for serialization?

Heh, I had the same question and is why I just opened an issue rather than a PR :) Maybe instead of focusing on headers, we could use `raw_headers` and pickle that, and either define an @property headers method or something. That might provide better compat any since since it lets you support raw_headers use too.

**Comment by JWCook** [comment]
Yeah, that seems to work well. WIP changes here if you want to review them: #29

**Comment by JWCook** [comment]
@akursar Changes are available in `aiohttp-client-cache 0.2.1`. Let me know if that works for you.

**Comment by akursar** [comment]
> @akursar Changes are available in `aiohttp-client-cache 0.2.1`. Let me know if that works for you.

It does indeed. Thanks!
