### ISSUE TITLE
Add possibility to check if request is a cache or not. 

### ISSUE THREAD

**Issue by Cikmo** [JWCook/aiohttp-client-cache#40]

**Comment by JWCook** [comment]
If you want to check if a response came from the cache, you can check its type:
```python
from aiohttp_client_cache import CachedResponse

response = await session.get('https://httpbin.org/get')
print(isinstance(response , CachedResponse))
```

Or did you mean checking if a specific request URL has already been cached?

**Comment by JWCook** [comment]
Did that answer your question, @Cikmo?

**Comment by JWCook** [comment]
Closing this for now. Let me know if you have any more questions about this.
