### ISSUE TITLE
Redis transparent config

### ISSUE THREAD

**Issue by wangha81** [JWCook/aiohttp-client-cache#50]
Please help to setup Redis with db args. Since RedisBackend accept `**kwargs` but its super ( CacheBackend ) did not, it couldn't setup Redis extra config bypassing `kwargs` with `RedisCache` and `create_redis_pool` function

**Comment by JWCook** [comment]
Sure, there are just a few more changes needed before adding `**kwargs` to `CacheBackend`, but connection args for Redis (and all other backends) will be working correctly in the next release.

**Comment by JWCook** [comment]
@wangha81 All connection args should be working now, and they're also [documented here](https://aiohttp-client-cache.readthedocs.io/en/latest/modules/aiohttp_client_cache.backends.redis.html).

Let me know if you have any more issues!
