### ISSUE TITLE
Add a bulk_delete method to each backend to speed up delete_expired_responses()

### ISSUE THREAD

**Issue by JWCook** [JWCook/aiohttp-client-cache#64]
Currently, all delete methods remove a single item at a time. `remove_expired_responses()` would be several times faster if each backend had a database-specific bulk delete method.

**Comment by AIGeneratedUsername** [comment]
I can find `remove_expired_responses` nowhere in the code. Where did it gone? Or where is it hidden?

**Comment by JWCook** [comment]
Right, I meant [delete_expired_responses](https://aiohttp-client-cache.readthedocs.io/en/latest/modules/aiohttp_client_cache.backends.base.html#aiohttp_client_cache.backends.base.CacheBackend.delete_expired_responses).
