### ISSUE TITLE
SQLite Backend not working as intended

### ISSUE THREAD

**Issue by FelixLanger** [JWCook/aiohttp-client-cache#73]
### The problem
Hello, I'm trying to use the sqlite backend to cache api queries. I'm trying to query one API, parse the results and with the parsed info am making another request. If I use the standard aiohttp.ClientSession() as well as the CachedSession with the base cache everything works. Changing the CachedSession to use the SQLite backend returns some errors like `Task <Task pending name='Task-3' coro=<task() running at ......`

### Expected behavior
I expected that changing the backend wouldn't raise those errors. I guess it could be due to the fact the code itself but since the standard Clientsession and CachedSession work, I assume the behaviour is not intended.

### Steps to reproduce the behavior
I build a minimum not working example with the googlebooks api.

```
import asyncio
from aiohttp_client_cache import CachedSession, SQLiteBackend
from datetime import timedelta


isbn_list = [
    '9780002005883',
    '9780002238304',
    '9780002261982',
    '9780006163831',
    '9780006178736',
    '9780006280897',
    '9780006280934',
    '9780006353287',
    '9780006380832',
    '9780006470229'
]

#Cache definition
cache = SQLiteBackend(
    cache_name='./.cache/books_cache.sqlite',
    expire_after=timedelta(days=100),
)

GOOGLE_BOOKS_URL = "https://www.googleapis.com/books/v1/volumes?q=isbn:{id}"


def parse_resposne(response):
    """Extract fields from API's response"""
    if response:
        item = response.get("items", [{}])[0]
        isbn = item["volumeInfo"]["industryIdentifiers"][0]["identifier"]
        return isbn


async def fetch_api(session, url, format=None):
    try:
        response = await session.get(url)
        if response.ok:
            if format == "json":
                return await response.json()
            else:
                return await response.text()
        else:
            return None
    except Exception as err:
        print(f"An error has occured: {err}")


async def task(session, isbn):
    response = await fetch_api(session, GOOGLE_BOOKS_URL.format(id = isbn), format="json")
    second_id = parse_resposne(response)
    metadata = await fetch_api(session, GOOGLE_BOOKS_URL.format(id = second_id))
    return metadata


async def main():
    async with CachedSession(cache=cache) as session:
        books_metadata = await asyncio.gather(*(task(session, isbn) for isbn in isbn_list))

if __name__ == "__main__":
    asyncio.run(main(), debug=True)
```

I'd really appreciate help to find out why this error occurs. I thought of giving other backends a try since this seems to be specific to the sqlite backend. I'm hesitant thought because the other solutions seem to require more initial setup. I'm also wondering if it's possible to have a persistant cache with the redis backend. I never used redis. I'm just curious if it's worth giving it a try instead of sqlite and cache persistance is a requirement for my project. 

Many thanks!

**Comment by JWCook** [comment]
Thanks for the details. Let me test this out and I'll get back to you shortly.

Regarding other backends, yes, Redis can be used as a persistent cache. If you're familiar with Docker, you can use the included `docker-compose.yml` to test out all the other backends if you want. But SQLite is the simplest to use in most cases.

**Comment by JWCook** [comment]
Looks like the probelm is that `SQLiteBackend` is being initialized outside the event loop created by `asyncio.run()`. If you move that inside your `main()` method, it works:
```python
async def main():
    cache = SQLiteBackend(cache_name='./.cache/books_cache.sqlite', expire_after=timedelta(days=100)) 
    async with CachedSession(cache=cache) as session:
        books_metadata = await asyncio.gather(*(task(session, isbn) for isbn in isbn_list)) 
```

I'm glad you brought this up, though, because I wasn't aware of that behavior with `SQLiteBackend`. I can probably update that with some more lazy initialization so you can create the cache at the module level.

**Comment by FelixLanger** [comment]
Wow, thank you very much for the quick response! moving it in the main function did the trick. Also many thanks pointing out the docker-compose file. I'll give the other backends a test in case sqlite doesn't fit my needs any more.
Keep up the good work!
