### ISSUE TITLE
'ClientResponse.text' has 'encoding' as 'Optional', but CachedResponse fails with 'encoding=None': 'self.encoding' does not return "utf-8" as a fallback  

### ISSUE THREAD

**Issue by AIGeneratedUsername** [JWCook/aiohttp-client-cache#81]
### The problem

`CachedResponse`  `self.encoding` does not return "utf-8" as a fallback if failed to detect encoding automatically
```
    async def text(self, encoding: Optional[str] = None, errors: str = "strict") -> str:
        """Read response payload and decode"""
>       return self._body.decode(encoding or self.encoding, errors=errors)
E       TypeError: decode() argument 'encoding' must be str, not None
```

### Expected behavior
 `self.encoding` must return "utf-8" if failed to detect encoding automatically 

### Steps to reproduce the behavior
  Call `await response.text()` without  `encoding` argument.

### Workarounds

No

### Environment
- aiohttp-client-cache version: =0.4.3
- Python version: 3.9
- Platform: Lubuntu 20.04

-----------

**aiohttp-client-cache** must be a drop-in replacement. **aiohttp** detects encoding via `self.get_encoding()` and returns `encoding = "utf-8"` if fails to detect.

**Comment by JWCook** [comment]
That's odd. This step here already calls `ClientResponse.get_encoding()` and falls back to uft-8 if that fails:
https://github.com/JWCook/aiohttp-client-cache/blob/d40c02bb8467c6b8327871f24003e8d753c68452/aiohttp_client_cache/response.py#L83-L88

What patch version are you using? That fix was added in `0.4.2` (#75).

I can update `CachedResponse.get_encoding()` and `CachedResponse.text()` to address that, but I can't seem to reproduce a case where `CachedResponse.encoding` is `None`.

**Comment by AIGeneratedUsername** [comment]
I still can not find the bug, but most likely the problem is on my side.

**Comment by AIGeneratedUsername** [comment]
**Solved: most likely something weird was cached and I got the error again and again for specific URL**
