### ISSUE TITLE
Add support for streaming requests

### ISSUE THREAD

**Issue by AIGeneratedUsername** [JWCook/aiohttp-client-cache#82]
### The problem

https://docs.aiohttp.org/en/stable/streams.html#asynchronous-iteration-support

```
response_bytes = b""
while chunk := await response.content.readany():
    response_bytes += chunk

assert len(response_bytes) > 0
```

**aiohttp** works fine, but **aiohttp-client-cache** returns always `b""` for any URL

### Expected behavior

Read bytes from response the same as **aiohttp** do.

### Steps to reproduce the behavior

Try to request https://httpbin.org/stream-bytes/10

### Workarounds

I do not know

### Environment
- aiohttp-client-cache version: 0.4
- Python version: 3.9
- Platform: Lubuntu 20.04

**Comment by AIGeneratedUsername** [comment]
Is there at least one working way to read bytes?

**Comment by JWCook** [comment]
A little more work is required to support streaming requests. What you're seeing is response content that's already been read (so it can be stored in the cache), so there's nothing left to iterate over.

There's an implementation for this with `requests` in [requests-cache](https://github.com/reclosedev/requests-cache), and I imagine the solution will be similar with `aiohttp`:
* For the original response, reset the file pointer after reading
* For the cached response, load the response body into a file-like object so it behaves like the original response

I'll look into this soon.

I can't think of a good workaround for this at the moment, so until this is fixed it's probably best to disable the cache for specific streaming requests you need to make (using `with CachedSession.disabled()`).

**Comment by AIGeneratedUsername** [comment]
Thank you for feedback.

> I can't think of a good workaround for this at the moment, so until this is fixed it's probably best to disable the cache for specific streaming requests you need to make (using with CachedSession.disabled()).

I've tried it. I think that `disabled()` only affects the cache checking, but a response is still read as you described. I t does not help.

I  **aiohttp-client-cache** only in tests for now. I was able to temporary avoid the problem by patching session object and reverting it back only during my "request_bytes" network calls.

**Comment by JWCook** [comment]
I spent a bit more time looking into this, and it looks like emulating a [StreamReader](https://github.com/aio-libs/aiohttp/blob/09ac1cbb4c07b4b3e1872374808512c9bc52f2ab/aiohttp/streams.py#L94) will be more complicated than just throwing a `BytesIO` object at it.

I think this is an important feature, so I definitely plan to add it, but it will take some more time for me to better understand aiohttp internals so I can do this in a way that's not too hacky or fragile.

**Comment by JWCook** [comment]
Despite the [warning](https://docs.aiohttp.org/en/stable/streams.html#aiohttp.StreamReader) that _"User should never instantiate streams manually"_, I think we can create a StreamReader manually and feed the cached data into it using [feed_data()](https://github.com/aio-libs/aiohttp/blob/09ac1cbb4c07b4b3e1872374808512c9bc52f2ab/aiohttp/streams.py#L239), and after that it _should_ behave the same as the original stream.

So far I've tested it with async and chunked iteration, and it seems to work fine. I could be missing something, though, and will need to do some more testing.

**Comment by JWCook** [comment]
Streaming request support is now in the latest pre-release build (0.5.0.dev2)

**Comment by JWCook** [comment]
@AIGeneratedUsername
Streaming request support is now in the latest pre-release build (0.5.0.dev2).

**Comment by AIGeneratedUsername** [comment]
I just installed `0.5.0` with the `pip install git+https://github.com/JWCook/aiohttp-client-cache`. Is the future included in it?

Requesting bytes is still broken when I enable "aiohttp-client-cache". I will try to provide more details again.
